# Generated by Django 5.0.2 on 2025-12-05 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_escolar_api', '0003_alumnos_maestros'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nrc', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('nombre', models.CharField(max_length=255, null=True)),
                ('hora_inicial', models.TimeField(blank=True, null=True)),
                ('hora_final', models.TimeField(blank=True, null=True)),
                ('creditos', models.IntegerField(blank=True, null=True)),
                ('carrera', models.CharField(blank=True, max_length=255, null=True)),
                ('salon', models.CharField(blank=True, max_length=15, null=True)),
                ('seccion', models.CharField(blank=True, max_length=3, null=True)),
                ('dias', models.TextField(blank=True, null=True)),
                ('creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('update', models.DateTimeField(blank=True, null=True)),
                ('profesor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_escolar_api.maestros')),
            ],
        ),
    ]
